version: "3"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus 
    volumes: 
      - /etc/prometheus:/etc/prometheus 
      - prometheus-data:/prometheus 
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml" 
    ports: 
      - '9089:9090'
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    volumes:
      - /home/promtailloki/loki:/etc/loki
    command: config.file=/etc/loki/loki-config.yaml
  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/promtailloki/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  cadvisor:
    image: zcube/cadvisor       
    container_name: cadvisor
#   ports:
#     - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
