global: 
  scrape_interval: 5s 
 
scrape_configs: 
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['docker-metrics-dashboard-prometheus-1:9090'] 
  - job_name: 'node-exporter' 
    static_configs: 
      - targets : ['docker-metrics-dashboard-node-exporter-1:9100']
  - job_name: 'cAdvisor' 
    static_configs: 
      - targets: ['docker-metrics-dashboard-cadvisor-1:8080']

